from enum import Enum, auto


class Intent(Enum):
    GREETING = auto()
    FAREWELL = auto()
    TIME = auto()
    DATE = auto()
    DATETIME = auto()
    TASK_ADD = auto()
    TASK_LIST = auto()
    TASK_DELETE = auto()
    TASK_COMPLETE = auto()
    NOTE_ADD = auto()
    NOTE_LIST = auto()
    NOTE_DELETE = auto()
    WEATHER = auto()
    CALCULATE = auto()
    TIMER_SET = auto()
    TIMER_CANCEL = auto()
    REMINDER_ADD = auto()
    REMINDER_LIST = auto()
    REMINDER_DELETE = auto()
    HELP = auto()
    SETTINGS = auto()
    WEB_SEARCH = auto()
    CAMERA_SHOW = auto()
    CAMERA_LIST = auto()
    CAMERA_ADD = auto()
    RESTAURANT = auto()
    EARN_MONEY = auto()
    RESEARCH = auto()
    PRESENTATION_CREATE = auto()
    CHAT = auto()
    UNKNOWN = auto()
